services:
  mysql:
    container_name: some-mysql
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - prestashop_network
    volumes:
      - dbdata:/var/lib/mysql

  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:latest
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      PS_LANGUAGE: es
      PS_COUNTRY: es
      DB_SERVER: ${DB_SERVER}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_PASSWD}
      PS_INSTALL_AUTO: 1
      PS_FOLDER_INSTALL: install
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN}
      ADMIN_MAIL: ${ADMIN_MAIL}
      ADMIN_PASSWD: ${ADMIN_PASSWD}
      PS_DOMAIN: localhost:8080
    volumes:
      - prestashop_data:/var/www/html
    networks:
      - prestashop_network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: ${DB_SERVER}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWD}
    networks:
      - prestashop_network

networks:
  prestashop_network:

volumes:
  dbdata:
  prestashop_data: